@startuml

title Usecase for Information system

' left to right direction

actor Користувач
actor Архітектор
actor Адміністратор


Архітектор -|> Користувач 

rectangle Software {

    usecase (Перевірити проект)
    usecase (Авторизувати користувача)
    usecase (Додати архітекрурний проект)

    (Додати архітекрурний проект) .> (Авторизувати користувача) : include
    (Перевірити проект) .> (Додати архітекрурний проект) : extends
    
    Адміністратор -- (Перевірити проект)
    Користувач -- (Авторизувати користувача)
    Архітектор -- (Додати архітекрурний проект)


}

@enduml
